routes/web.php
<?php

use App\Http\Controllers\Admin\DeviceCategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ManagerController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\RecordPlanController;
use App\Http\Controllers\Admin\RecordPlan\RecordPlanController2;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\TechnicalCameraController;
use App\Http\Controllers\Admin\ReporterController;
use App\Http\Controllers\Admin\CameraController;
use App\Http\Controllers\Admin\DriverController;
use App\Http\Controllers\Admin\CarController;
use App\Http\Controllers\Admin\DeviceController;
use App\Http\Controllers\Admin\OutsourceTypeController;
use App\Http\Controllers\Admin\OutsourceController;
use App\Http\Controllers\Admin\PlanController;
use App\Http\Controllers\Admin\StatementController;
use App\Http\Controllers\Admin\ContractController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Livewire\Counter;
use App\Http\Livewire\Greeting;
use App\Http\Livewire\Base;
use App\Http\Livewire\Calendar;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\StageController;
use App\Http\Controllers\Admin\ExampleNoteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/','DashboardController@index');

Route::group(['prefix' => 'basic-ui'], function(){
    Route::get('accordions', function () { return view('pages.basic-ui.accordions'); });
    Route::get('buttons', function () { return view('pages.basic-ui.buttons'); });
    Route::get('badges', function () { return view('pages.basic-ui.badges'); });
    Route::get('breadcrumbs', function () { return view('pages.basic-ui.breadcrumbs'); });
    Route::get('dropdowns', function () { return view('pages.basic-ui.dropdowns'); });
    Route::get('modals', function () { return view('pages.basic-ui.modals'); });
    Route::get('progress-bar', function () { return view('pages.basic-ui.progress-bar'); });
    Route::get('pagination', function () { return view('pages.basic-ui.pagination'); });
    Route::get('tabs', function () { return view('pages.basic-ui.tabs'); });
    Route::get('typography', function () { return view('pages.basic-ui.typography'); });
    Route::get('tooltips', function () { return view('pages.basic-ui.tooltips'); });
});

Route::group(['prefix' => 'charts'], function(){
    Route::get('chartjs', function () { return view('pages.charts.chartjs'); });
    Route::get('morris', function () { return view('pages.charts.morris'); });
    Route::get('flot', function () { return view('pages.charts.flot'); });
    Route::get('google-charts', function () { return view('pages.charts.google-charts'); });
    Route::get('sparklinejs', function () { return view('pages.charts.sparklinejs'); });
    Route::get('c3-charts', function () { return view('pages.charts.c3-charts'); });
    Route::get('chartist', function () { return view('pages.charts.chartist'); });
    Route::get('justgage', function () { return view('pages.charts.justgage'); });
});

Route::group(['prefix' => 'tables'], function(){
    Route::get('basic-table', function () { return view('pages.tables.basic-table'); });
    Route::get('data-table', function () { return view('pages.tables.data-table'); });
    Route::get('js-grid', function () { return view('pages.tables.js-grid'); });
    Route::get('sortable-table', function () { return view('pages.tables.sortable-table'); });
});

Route::group(['prefix' => 'icons'], function(){
    Route::get('material', function () { return view('pages.icons.material'); });
    Route::get('flag-icons', function () { return view('pages.icons.flag-icons'); });
    Route::get('font-awesome', function () { return view('pages.icons.font-awesome'); });
    Route::get('simple-line-icons', function () { return view('pages.icons.simple-line-icons'); });
    Route::get('themify', function () { return view('pages.icons.themify'); });
});

//-------------------------------------------------------------------------------------------------------------------------------------------------------



Auth::routes([
    'register' => false, // Registration Routes...
    'verify' => false, // Email Verification Routes...
]);

//Route::get('/', function () {
//    return view('welcome');
//});

Route::group(['middleware' => ['auth', 'get.menu']], function () {
    Route::get('/calendars', Calendar::class)->name('calendar');
//    Route::get('/', Calendar::class)->name('home');
    Route::get('/', [RecordPlanController::class, 'index'])->name('home');

    //change-password'
    Route::group([
        'prefix' => 'change-password',
        'as' => 'change-password.',
    ], function(){
        Route::get('', [ChangePasswordController::class, 'index'])->name('index');
        Route::post('store', [ChangePasswordController::class, 'store'])->name('store');
    });
    Route::get("planned_mail", [\App\Http\Controllers\Admin\MailController::class, "sendDailyPlannedReportRecordPlans"]);
    Route::get("executed_mail", [\App\Http\Controllers\Admin\MailController::class, "sendDailyExecutedReportRecordPlans"]);

    //Record plans
    Route::group([
        'prefix' => 'record-plans2',
        'as' => 'record-plans2.',
    ], function(){
        Route::get('', [RecordPlanController2::class, 'index'])->name('index');
    });

    Route::group([
        'prefix' => 'record-plans',
        'as' => 'record-plans.',
    ], function(){
        Route::get('', [RecordPlanController::class, 'index'])->name('index');
        Route::get('{id}/show', [RecordPlanController::class, 'showRecordPlan'])->name('show');
        Route::get('create', [RecordPlanController::class, 'create'])->name('create');
        Route::post('', [RecordPlanController::class, 'store'])->name('store');
        Route::get('{id}/edit', [RecordPlanController::class, 'editRecordPlan'])->name('edit');
        Route::put('{id}/update', [RecordPlanController::class, 'update'])->name('update');
        Route::delete('{id}/destroy', [RecordPlanController::class, 'destroy'])->name('destroy');
        Route::post('{id}/restore', [RecordPlanController::class, 'restore'])->name('restore');
        Route::post('{id}/update-status', [RecordPlanController::class, 'updateGeneralStatus'])->name('update-status');
        Route::get('import', [RecordPlanController::class, 'import'])->name('import');
        Route::post('import', [RecordPlanController::class, 'importStore'])->name('store-import');
        Route::get('export', [RecordPlanController::class, 'export'])->name('export');
        Route::get("downloadFile/{fileName}", [RecordPlanController::class, "downloadFile"])->name('dowloadFile');

        Route::post("{id}/update-offer-member", [RecordPlanController::class, "updateOfferMember"]);

        Route::get("test", [RecordPlanController::class, "autoCreateRecordPlanRecurring"]);
    });

    //Calendar
    Route::middleware([])->group(function () {
        Route::group(['prefix' => 'calendars'], function () {
            Route::get('/record-plans', [RecordPlanController::class, 'getEvents']);
        });
    });

    // Group
    Route::group([
        "middleware" => "checkRole:superadmin",
        'prefix' => 'menus',
        'as' => 'menus.',
//        "middleware" =>  ['can:is_admin']
    ], function () {
        Route::get('', [MenuController::class, 'index'])->name('index');
        Route::get('{id}/show', [MenuController::class, 'show'])->name('show');
        Route::get('create', [MenuController::class, 'create'])->name('create');
        Route::post('', [MenuController::class, 'store'])->name('store');
        Route::get('{id}/edit', [MenuController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [MenuController::class, 'update'])->name('update');
        Route::delete('{id}/destroy', [MenuController::class, 'destroy'])->name('destroy');
        Route::post('{id}/restore', [MenuController::class, 'restore'])->name('restore');
    });

    // Departments
    Route::group([
        "middleware" => "checkRole:superadmin",
        'prefix' => 'departments',
        'as' => 'departments.',
//        "middleware" =>  ['can:is_admin']
    ], function () {
        Route::get('', [DepartmentController::class, 'index'])->name('index');
        Route::get('{id}/show', [DepartmentController::class, 'show'])->name('show');
        Route::get('create', [DepartmentController::class, 'create'])->name('create');
        Route::post('', [DepartmentController::class, 'store'])->name('store');
        Route::get('{id}/edit', [DepartmentController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [DepartmentController::class, 'update'])->name('update');
        Route::delete('{id}/destroy', [DepartmentController::class, 'destroy'])->name('destroy');
        Route::post('{id}/restore', [DepartmentController::class, 'restore'])->name('restore');
    });

    // Permission management - access and features
    Route::group([
        'as' => 'permissions.'
    ], function () {
        Route::get('access-permissions', [PermissionController::class, 'access'])->name('access');
        Route::put('access-permissions/save', [PermissionController::class, 'saveAccessPermissions'])->name('access.save');
        Route::put('access-permissions/remove', [PermissionController::class, 'removeAccessPermissions'])->name('access.remove');
        Route::get("feature-permissions", [PermissionController::class, 'features'])->name('features');

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;

class Department extends Model
{
    use HasFactory;
    use SoftDeletes;
    use HasRoles;

    protected $table = "departments";
    protected $fillable = ["id", "name", "description", "parent_id", "code", "status", "note", "created_at", "updated_at", "created_by", "updated_by", "deleted_at"];
    // Define default guard name for laravel-permission, prevent error when creating roles/permissions
    protected $guard_name = "web";

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }
}

app/Http/Controllers/API/schemas/department/DepartmentResourceSchema.php
<?php

/**
 * @OA\Schema(
 *      title="Department Resource",
 *      description="Department Resource",
 *      type="object",
 * )
 */
class DepartmentResourceSchema
{

    /**
     * @OA\Property(
     *      description="id của department",
     *      example="2"
     * )
     * @var integer
     */
    public $id;

    /**
     * @OA\Property(
     *      description="tên của department",
     *      example="Phòng sản xuất"
     * )
     * @var string
     */
    public $name;

    /**
     * @OA\Property(
     *      description="mô tả department",
     *      example="Phòng sản xuất"
     * )
     * @var string
     */
    public $description;

    /**
     * @OA\Property(
     *      description="parent id",
     *      example="0"
     * )
     * @var integer
     */
    public $parent_id;

    /**
     * @OA\Property(
     *      description="code",
     *      example="production"
     * )
     * @var string
     */
    public $code;

    /**
     * @OA\Property(
     *      description="code",
     *      example="1"
     * )
     * @var integer
     */
    public $status;

    /**
     * @OA\Property(
     *      description="ghi chú",
     *      example="ghi chú"
     * )
     * @var string
     */
    public $note;
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\PaginateForArray;
use App\Helpers\TreeBuilder;
use App\Http\Resources\DepartmentResource;
use App\Repositories\DepartmentRepository;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    protected $modelDisplayName = 'department';
    protected $prefix = 'departments';
    protected $modelClass = "App\Models\Department";

    public function __construct(DepartmentRepository $departmentRepository)
    {
        parent::__construct();
        $this->selfRepository = $departmentRepository;
    }

    /**
     * Tạo cấu trúc dữ liệu phòng ban dạng cây
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $allParams = $request->except('page');

        $data = $this->selfRepository->allQuery($this->makeQueryParams($allParams))->get();
        if ($request->is_active == -1) {
            $data = $this->selfRepository->allQuery($this->makeQueryParams($allParams))->onlyTrashed()->get();
        }
        $canBuildTree = $this->checkIfDataCanBuildTree($data);

        if($canBuildTree){
            $tree = TreeBuilder::buildTree($data);
        }else{
            $tree = $data;
        }

        return view($this->viewNamespace . $this->prefix . '.list')->with([
            "data" => $data,
            "tree" => $tree,
            "allParams" => $allParams
        ]);
    }

    public function checkIfDataCanBuildTree($list, $parentKey = "parent_id"){
        //xử lý data xem có cần build tree hay k
        $referList = array();
        foreach ($list as $item){
            $referList[$item[$parentKey]][] = $item;
        }
        if(array_key_exists(0, $referList)){
            return true;
        }
        return false;
    }
}

resources/views/pages/departments/detail.blade.php
@extends('layouts.detail')

@section('content')
        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-12">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i>
                        <strong>
                            @if(!isset($data))
                            @elseif(isset($editable) && $editable == true)
                            @else
                                {{ __('Manager detail') }}
                            @endif
                        </strong>
                    </div>
                    <div class="card-body">
                        <br>
                        <form method="POST" novalidate action="/users/{{ $data->id }}">
                            @csrf
                            @method('PUT')
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <svg class="c-icon c-icon-sm">
                                          <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-user"></use>
                                      </svg>
                                    </span>
                                </div>
                                <input class="form-control" type="text" placeholder="{{ __('Name') }}" name="name" value="{{ $data->name }}" required autofocus>
                            </div>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">@</span>
                                </div>
                                <input class="form-control" type="text" placeholder="{{ __('E-Mail Address') }}" name="email" value="{{ $data->email }}" required>
                            </div>
                            <button class="btn btn-block btn-success" type="submit">{{ __('Save') }}</button>
                            <a href="{{ route('managers.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a>
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

@section('javascript')

@endsection

resources/views/pages/departments/list.blade.php
@extends('layouts.list')

@section("buttons")
    @can('create', app($modelClass))
        @include("partials.text-btn.create-group-btn")
    @endcan
@endsection

@section("sub-header-content")
    {{__('data_field_name.action.manage', ["dataName" => __('data_field_name.model_name.'.$modelDisplayName)])}}
@endsection

@section('table-list')
    <div class="row">
        <div class="gw-sidebar">
            <div id="gw-sidebar" class="gw-sidebar">
                <div class="nano-content">
                    <ul class="gw-nav gw-nav-list">
                        <input type="hidden" name="access-permission-route" value="{{route("permissions.access")}}" />
                        <input type="hidden" name="feature-permission-route" value="{{route("permissions.features")}}" />
                        <!-- <li class="init-un-active"> <a href="javascript:void(0)"><span class="gw-menu-text">GĐ - Giám đốc</span> </a> </li> -->
                        @foreach($tree as $department)
                        <x-department-item :item=$department level=0></x-department-item>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        function toggleIcon(e) {
            $(e.target)
                .prev(".panel-heading")
                .find(".more-less")
                .toggleClass("fa-arrow-up fa-arrow-down");
        }
        $(".panel-group").on("hidden.bs.collapse", toggleIcon);
        $(".panel-group").on("shown.bs.collapse", toggleIcon);

    </script>
    <script>
        var toggler = document.getElementsByClassName("caret");
        var i;

        for (i = 0; i < toggler.length; i++) {
            toggler[i].addEventListener("click", function() {
                this.parentElement.querySelector(".nested").classList.toggle("active");
                this.classList.toggle("caret-down");
            });
        }
    </script>
    <script>
        function toggleIcon(e) {
            $(e.target)
                .prev(".menu-parent")
                .find(".more-less")
                .toggleClass("fa-arrow-up fa-arrow-down");
        }
        $(".menu-parent").on("hidden.bs.collapse", toggleIcon);
        $(".menu-parent").on("shown.bs.collapse", toggleIcon);

    </script>
    <script>
        let accessRoute = document.getElementsByName("access-permission-route")[0].value
        let featureRoute = document.getElementsByName("feature-permission-route")[0].value
        console.log(accessRoute,featureRoute)
        document
            .querySelectorAll("button[data-action='access-permission']")
            .forEach(el => el.addEventListener("click", (e) => {
                e.stopImmediatePropagation()
                e.stopPropagation()
                const deparmentId = el.dataset.departmentId

                window.location.href = `${accessRoute}?department=${deparmentId}`
            }))
        document
            .querySelectorAll("button[data-action='feature-permission']")
            .forEach(el => el.addEventListener("click", (e) => {
                e.stopImmediatePropagation()
                e.stopPropagation()
                const deparmentId = el.dataset.departmentId

                window.location.href =`${featureRoute}?department=${deparmentId}`
            }))
    </script>
@endpush